title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
plugins:
  - jekyll-feed


data:
 - name: "高階13色流式細胞儀"
   id: "1"
   nameEN: "LSR II Flow Cytometer"
   img: "https://media.beckman.com/-/media/flow-cytometry/products/instruments/dxflex/flow-cytometer-dxflex-1.jpg?rev=07c4b750319b44aab1aaa1cf8439121b"
   link: "javascript: void(0)"
   category: "儀器"
 - name: "類流式影像自動擷取定量系統"
   id: "2"
   nameEN: "TissueFAXS"
   img: "https://lh5.googleusercontent.com/proxy/k3P14K_CbawFisWuRColFwsWcbNgJGv8d3V6QFhnBBo_6csGAYpgzgHiA36e9WdTrlqKJmgWc2grKTQDzAiUZnXdadjMH9M"
   link: "javascript: void(0)"
   category: "儀器"
 - name: "TissueFAXS分析軟體"
   id: "3"
   nameEN: "TissueFAXS Analysis Software"
   img: "https://lh5.googleusercontent.com/proxy/k3P14K_CbawFisWuRColFwsWcbNgJGv8d3V6QFhnBBo_6csGAYpgzgHiA36e9WdTrlqKJmgWc2grKTQDzAiUZnXdadjMH9M"
   link: "javascript: void(0)"
   category: "系統軟體"
 - name: "雷射共軛焦顯微鏡"
   id: "4"
   nameEN: "FV 1000 Confocal Microscope"
   img: "https://www1.cgmh.org.tw/intr/intr5/c6s210/images/%E5%85%B1%E8%BB%9B%E7%84%A6%E9%A1%AF%E5%BE%AE%E9%8F%A1_1_clip_image001.jpg"
   link: "javascript: void(0)"
   category: "顯微鏡"
 - name: "雷射共軛焦顯微鏡"
   id: "5"
   nameEN: "LSM 700 Confocal Microscope"
   img: "https://live.staticflickr.com/7043/6908567127_efc1715fd7_h.jpg"
   link: "javascript: void(0)"
   category: "顯微鏡"
 - name: "細胞內離子偵測系統"
   id: "6"
   nameEN: "Cell^R Excellence System"
   img: "https://crrd.kmu.edu.tw/images/fancybox/cellr/cellrex2big.jpg"
   link: "javascript: void(0)"
   category: "儀器"
 - name: "正立螢光顯微鏡"
   id: "7"
   nameEN: "AxioPlan2 Upright"
   img: "https://www.bostonind.com/image/cache/catalog/products_2023/ZeissAxioplan2(6)-800x600w.jpg.webp"
   link: "javascript: void(0)"
   category: "顯微鏡"
 - name: "螢光共振能量轉移顯微系統"
   id: "8"
   nameEN: "Leica M205FA Fluorescence"
   img: "https://www.major.com.tw/webfiles/79bede13-2f17-4748-82e9-7ec10dff3dd4.png"
   link: "javascript: void(0)"
   category: "顯微鏡"
 - name: "多層次螢光影像擷取與分析系統"
   id: "9"
   nameEN: "ImageXpress"
   img: "https://www.kimforest.com/upload/product/pic/20190530120432hty.png"
   link: "javascript: void(0)"
   category: "儀器"
 - name: "多層次螢光影像擷取與分析系統"
   id: "10"
   nameEN: "Offline Analysis System"
   img: "https://www.moleculardevices.com/media_11641411b16d0c432b2b099ea0d25df9845cf6233.jpeg?width=750&format=jpeg&optimize=medium"
   link: "javascript: void(0)"
   category: "系統軟體"
 - name: "高階三維重建影像分析軟體"
   id: "11"
   nameEN: "Imaris"
   img: "https://crrd.kmu.edu.tw/images/test/5b9897d7-158d-41b6-877a-e6a2afd53394_web.jpg"
   link: "javascript: void(0)"
   category: "系統軟體"
 - name: "核磁共振儀"
   id: "12"
   nameEN: "Varian-NMR-600MHz"
   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAZPr6pOsohCROM7lLA-w3V4bprXXoEBjo3Q&s"
   link: "javascript: void(0)"
   category: "儀器"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
